name: Build

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-base.yml

  upload-artifacts:
    needs: build
    runs-on: ubuntu-latest
    env:
      PROJECT: ResoniteModUpdater
    strategy:
      matrix:
        include:
          - platform: linux-x64
          - platform: win-x64
          - platform: win-x64
            is-portable: true
    steps:
      - name: Download Build Outputs
        uses: actions/download-artifact@v5
        with:
          name: build-outputs-${{ matrix.platform }}${{ matrix.is-portable && '-portable' || '' }}
          path: .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT }}-${{ matrix.platform }}${{ matrix.is-portable && '-portable' || '' }}-${{ needs.build.outputs.version }}
          path: |
            releases.*.json
            *.nupkg
            *.zip
            *.exe
            *.AppImage

  cleanup:
    needs: [build, upload-artifacts]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Delete Intermediate Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build-outputs-*