name: Build and Release

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-base.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Build Outputs (Linux)
        uses: actions/download-artifact@v4
        with:
          name: build-outputs-linux-x64
          path: .

      - name: Download Build Outputs (Windows)
        uses: actions/download-artifact@v4
        with:
          name: build-outputs-win-x64
          path: .

      - name: Download Build Outputs (Windows Portable)
        uses: actions/download-artifact@v4
        with:
          name: build-outputs-win-x64-portable
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          generate_release_notes: false
          name: v${{ needs.build.outputs.version }}
          tag_name: v${{ needs.build.outputs.version }}
          target_commitish: ${{ github.sha }}
          files: |
            releases.*.json
            *.nupkg
            *.zip
            *.exe
            *.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    needs: [build, release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Delete Intermediate Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build-outputs-*